on:
  workflow_dispatch:

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Git credentials
        run: |
          git config --global user.email "${{ secrets.GITHUB_EMAIL }}"
          git config --global user.name "${{ secrets.GITHUB_USERNAME }}"
          git config --global url."https://${{ secrets.GITHUBPAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      # Checkout the remote repo with a `repo` scoped PAT
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUBPAT }}
          repository: dhananjayajayashankajkh/SonarTest
          ref: test01

      # Make changes to pull request here

      - name: Update Author Information
        run: |
          echo "${{ env.GIT_COMMIT_AUTHOR_NAME }}" > AUTHOR
          echo "${{ env.GIT_COMMIT_AUTHOR_EMAIL }}" >> AUTHOR

      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUBPAT }}  # Ensure this matches the secret name
          branch: "main"  # Source branch
          base: "test01"  # Target branch
          title: "Demo for Auto PR"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          body: "This is to show automatic PR creation"
          delete-branch: true
