name: automated pull

on:
  workflow_dispatch:


jobs:
  updateAuthor:
     runs-on: ubuntu-latest
     steps:
       - name: checking out code
         uses: actions/checkout@v4

       - name: extract git commit data
         uses: rlespinasse/git-commit-data-action@v1.x

       - name: Update Author Information
         run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

       - name: Raise PR
         uses: peter-evans/create-pull-request@v3
         with:
            branch: "main"
            base: test
            title: "demo for auto pr"
            committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
            autor: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
            body:
              This is to show automatic PR creation
            token: ${{ secrets.GITHUBPAT }}
            delete-branch: true
            

        
