name: Automated Pull Request

on:
  workflow_dispatch:

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUBPAT }}
          persist-credentials: false

      - name: Extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Debug Commit Data
        run: |
          echo "Commit Author Name: ${{ env.GIT_COMMIT_AUTHOR_NAME }}"
          echo "Commit Author Email: ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"

      - name: Update Author Information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Set up Git
        run: |
          git config --global user.name "${{ env.GIT_COMMIT_AUTHOR_NAME }}"
          git config --global user.email "${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"

      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "test"
          base: main
          title: "Demo for Auto PR"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          body: "This is to show automatic PR creation"
          token: ${{ secrets.GITHUBPAT }}
          delete-branch: true
