# File: .github/workflows/pull-request.yml
on:
  push:
    branches:
      - develop

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.PAT_TOKEN }}" | gh auth login --with-token
        
      - name: Create pull request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: "test"
